server:
  port: 1005
spring:
  application:
    name: producer-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1003/eureka/,http://peer2:1004/eureka/
  instance:
    lease-renewal-interval-in-seconds: 40 #服务续约任务调用间隔为40s，默认为30s
    lease-expiration-duration-in-seconds: 120 #服务失效时间为120s，默认为90s